### ISSUE TITLE
Characters after a link reversed.

### ISSUE THREAD

**Issue by bjhijmans** [thephpleague/commonmark-ext-autolink#13]
In the following example:
`[image src='<image>' caption='source: ( https://www.example.com/test). ']`

The resulting caption for the image is:
`source: (https://www.example.com/test.) `
The . and ) at the end are reversed. 

This only happens with some links, specifically the /test in the example was necessary to reproduce the error. I think the closing paren that gets chopped off in processAutoLinks() needs to be prepended to $leftovers instead of appended. But I'm unsure if that is correct in all cases.

**Comment by colinodell** [comment]
> I think the closing paren that gets chopped off in processAutoLinks() needs to be prepended to $leftovers instead of appended.

Yep, that does seem to be the issue.  Thanks for the detailed bug report!  I'll get this released in v1.0.1 in a few minutes :)

**Comment by colinodell** [comment]
Done! https://github.com/thephpleague/commonmark-ext-autolink/releases/tag/v1.0.1
